import { ThemeSwitcher } from "@/components/theme-switcher";
import { ClerkProvider } from "@/providers/clerk-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import {
  ClerkLoaded,
  ClerkLoading,
  OrganizationSwitcher,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ClerkProvider>
            <header className="flex justify-end items-center p-4 gap-4 h-16 border-b">
              <ThemeSwitcher />
              <SignedOut>
                <SignInButton mode="modal" />
                <SignUpButton mode="modal" />
              </SignedOut>
              <SignedIn>
                <OrganizationSwitcher />
                <UserButton />
              </SignedIn>
            </header>
            <main className="p-8">
              <ClerkLoading>
                <p>Loading...</p>
              </ClerkLoading>
              <ClerkLoaded>{children}</ClerkLoaded>
            </main>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
